Enable CI
sgrepo/celery-unique pull request #2
Opened 2017-04-28 19:22 UTC by hobarrera

Enable CI for running tests and deploying.

Note: PR has been set to use `py3` as a base to simplify diffing, but should actually be merged to master after #1 gets merged.

2017-05-01 17:38 UTC, TylerHendrickson requested changes

2017-05-01 17:38 UTC, TylerHendrickson commented on setup.py
>      author='Tyler Hendrickson, Shiftgig Inc',
You should add yourself here and to the next line at some point

Edit: As-discussed, we should move to using a CONTRIBUTORS/AUTHORS file instead

2017-05-01 17:38 UTC, TylerHendrickson commented on README.rst
>  - A modified Task base class for Celery (provided by this package)
List doesn't appear to be rendering in rst

2017-05-01 17:38 UTC, TylerHendrickson commented on README.rst
> +celery-unique
As-discussed, perhaps we can use `pandoc` to assist with automatically converting `README.md` to `README.rst` as a deployment step.  If that seems feasible, we should change this file back to markdown.

2017-05-01 17:38 UTC, TylerHendrickson commented on .travis.yml
> +    user: hobarrera
Will provide a Shiftgig user and credentials for you

2017-05-03 15:53 UTC, hobarrera commented on .travis.yml
> +    user: hobarrera
Ping?

2017-05-03 15:54 UTC, hobarrera commented
I think I screwed up since I hadn't pushed my latest working branch for your last review, and I'd rewritten some commits locally (thought I hadn't pushed them, sorry).

Anyway, this is ready for a second round or review.

2017-05-03 19:37 UTC, hobarrera commented on setup.py
>      author='Tyler Hendrickson, Shiftgig Inc',
See #3

2017-05-03 19:55 UTC, TylerHendrickson approved these changes

2017-05-03 20:40 UTC, merged