Add a LICENCE file
sgrepo/celery-unique pull request #4
Opened 2017-05-03 19:45 UTC by hobarrera

2017-05-03 19:52 UTC, TylerHendrickson requested changes
@hobarrera Two quick changes for you

2017-05-03 19:52 UTC, TylerHendrickson commented on LICENCE
> +Copyright (c) 2015-2017 Shiftgig Inc.
I like the practice of putting the license type as the first line of the `LICENSE` file (followed by a blank line).  At the very least, it provides easy reference (for us as well as anyone looking for examples).

2017-05-03 19:52 UTC, TylerHendrickson commented on LICENCE
> +Copyright (c) 2015-2017 Shiftgig Inc.
Missing comma- should be
```
Copyright (c) 2015-2017, Shiftgig Inc.
```

2017-05-03 19:54 UTC, hobarrera commented on LICENCE
> +Copyright (c) 2015-2017 Shiftgig Inc.
I haven't seen that before, but I like the idea since it makes recognizing it *a lot* easier.

2017-05-03 19:54 UTC, hobarrera commented
Both things fixed.

2017-05-04 19:21 UTC, TylerHendrickson approved these changes

2017-05-04 21:20 UTC, TylerHendrickson approved these changes

2017-05-04 22:55 UTC, merged